In [382]:
import numpy as np
import pandas as pd
df = pd.read_csv('./data/USA_Housing.csv')
X_all = np.array(df.iloc[:,0:-2])
y_all = np.array(df.iloc[:,-2]).reshape((len(df), 1))

class Linear():
    def __init__(self, X, y, iters = 10000 ):
        self.X = np.concatenate((np.ones(y.shape), X),axis =1)
        self.y = y
        self.preds = np.zeros(y.shape)
        self.n = y.shape[0]
        self.loss = None
        self.lr = 0.0000000001
        self.beta = np.random.uniform(low=-1.0, high=1.0, size= (1, self.X.shape[1]) )  
        self.grad = np.random.uniform(low=-1.0, high=1.0, size= self.beta.shape )
        self.iters = iters
        
    def forward(self):
        self.preds = np.sum(self.X *self.beta, axis =1, keepdims=True)
        
    def backward(self):
        self.grad =2*  np.mean((self.preds - self.y)* self.X, axis=0, keepdims=True )
        self.beta = self.beta -  self.lr * self.grad       
        
    def calculate_loss(self):
        self.loss = np.mean( (self.y - self.preds)**2 )
        
    def fit(self):
        for _ in range(self.iters):
            self.forward()
            self.backward()
            self.calculate_loss()
            #print(self.loss)

linear= Linear(X_all, y_all)
linear.fit()
linear.beta


array([[ 0.91488902, 13.04194508,  1.05339481, -0.17015642, -0.54357686,
         9.71577893]])

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [379]:
class Linear():
    def __init__(self, X, y, iters = 10000 ):
        self.X = np.concatenate((np.ones(y.shape), X),axis =1)
        self.y = y
        self.preds = np.zeros(y.shape)
        self.n = y.shape[0]
        self.loss = None
        self.lr = 0.0000000001
        self.beta = np.random.uniform(low=-1.0, high=1.0, size= (1, self.X.shape[1]) )  
        self.grad = np.random.uniform(low=-1.0, high=1.0, size= self.beta.shape )
        self.iters = iters 
        
    def forward(self):
        self.preds = np.sum(self.X *self.beta, axis =1, keepdims=True)
        
    def backward(self):
        self.grad =2*  np.mean((self.preds - self.y)* self.X, axis=0, keepdims=True ) 
        self.beta = self.beta -  self.lr * self.grad       
        
    def calculate_loss(self):
        self.loss = np.mean( (self.y - self.preds)**2 )
        
    def fit(self):
        for _ in range(self.iters):
            self.forward()
            self.backward()
            self.calculate_loss()
            #print(self.loss) 

linear= Linear(X_all, y_all)
linear.fit()
linear.beta

array([[ 0.81940427, 13.04192667,  0.69367933, -0.43717147,  0.86693872,
         9.71577292]])

In [381]:
import matplotlib.pyplot as plt